#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
增强完整交易系统文档
添加更多实际案例和规则
"""

import json

def parse_json_file(file_path: str):
    """解析JSON文件"""
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        return data.get('messages', [])

def extract_key_messages(messages):
    """提取关键消息"""
    de_messages = []
    for msg in messages:
        author = msg.get('author', {})
        if author.get('nickname') == 'De.':
            content = msg.get('content', '')
            if len(content) > 20:  # 过滤太短的消息
                de_messages.append({
                    'content': content,
                    'timestamp': msg.get('timestamp', '')
                })
    return de_messages

def generate_enhanced_system():
    """生成增强版交易系统文档"""
    
    doc = []
    doc.append("=" * 80)
    doc.append("交易员 De. 的完整交易系统 - 最终增强版")
    doc.append("=" * 80)
    doc.append("")
    doc.append("本系统适用于：5分钟、15分钟、1小时时间框架")
    doc.append("")
    doc.append("**重要说明**：本系统基于De.的所有实际交易记录和规则总结，结合ICT、市场微观结构等成熟交易理论")
    doc.append("")
    
    # 一、系统概述
    doc.append("## 一、交易系统概述")
    doc.append("")
    doc.append("### 系统类型")
    doc.append("- **交易风格**: 区间震荡剥头皮交易")
    doc.append("- **主要标的**: BTC/USDT")
    doc.append("- **持仓时间**: 短线（几分钟到几小时）")
    doc.append("- **风险等级**: 中等（窄止损，快速进出）")
    doc.append("")
    doc.append("### 核心特点")
    doc.append("1. **多维度分析**: 趋势 + 流动性 + 市场结构 + 时间周期")
    doc.append("2. **多情景规划**: 考虑所有可能的市场走势，为每个情景准备交易计划")
    doc.append("3. **流动性优先**: 关注流动性被扫的情况，流动性被扫后重新评估市场")
    doc.append("4. **市场结构识别**: 识别供给区、需求区、派发、吸筹、养单行为")
    doc.append("5. **时间周期考虑**: 避免周末交易，考虑周五/周一效应")
    doc.append("6. **严格风险管理**: 止损 + 止盈 + 仓位管理 + 盈亏比≥2倍")
    doc.append("")
    
    # 二、多维度市场分析系统
    doc.append("## 二、多维度市场分析系统")
    doc.append("")
    
    doc.append("### 2.1 趋势分析（多时间框架确认）")
    doc.append("")
    doc.append("**分析步骤**：")
    doc.append("")
    doc.append("1. **日线级别趋势**（最重要）")
    doc.append("   - 判断：\"今天日线偏多\" 或 \"日线偏空\"")
    doc.append("   - 作用：确定大趋势方向")
    doc.append("   - 应用：大趋势向上，优先考虑多单；大趋势向下，优先考虑空单")
    doc.append("   - **规则**：如果大趋势与交易方向相反，风险极高")
    doc.append("")
    doc.append("2. **4小时趋势**")
    doc.append("   - 确认中期趋势")
    doc.append("   - 与日线趋势是否一致")
    doc.append("")
    doc.append("3. **1小时趋势**")
    doc.append("   - 确认短期趋势")
    doc.append("   - 用于1小时级别交易")
    doc.append("")
    doc.append("4. **15分钟趋势**")
    doc.append("   - 确认更短期趋势")
    doc.append("   - 用于15分钟级别交易")
    doc.append("")
    doc.append("5. **多时间框架一致性**")
    doc.append("   - 理想情况：所有时间框架趋势一致")
    doc.append("   - 不一致时：需要更谨慎，可能需要等待")
    doc.append("")
    doc.append("**实际案例**：")
    doc.append("- \"今天日线偏多\" → 大趋势向上，优先考虑多单")
    doc.append("- \"现在五分钟vwap压制，偏空\" → 5分钟级别偏空，但需要看日线")
    doc.append("- \"顺大逆小\" → 顺应大趋势，逆小趋势（突破单概率低）")
    doc.append("")
    
    doc.append("### 2.2 流动性分析（关键，必须分析）")
    doc.append("")
    doc.append("**流动性分析的重要性**：")
    doc.append("")
    doc.append("流动性被扫是De.系统中最关键的因素之一。流动性被扫后，市场方向可能发生重大变化。")
    doc.append("")
    doc.append("**流动性分析步骤**：")
    doc.append("")
    doc.append("1. **识别流动性区域**")
    doc.append("   - 大量挂单的位置 = 流动性区域")
    doc.append("   - 常见位置：")
    doc.append("     * 周五/周一的高点/低点")
    doc.append("     * 周内高低点")
    doc.append("     * 日内高低点")
    doc.append("     * 波段高低点")
    doc.append("")
    doc.append("2. **检查流动性是否被扫**")
    doc.append("   - \"早上已经扫了，周五的高点\"")
    doc.append("   - \"1074扫完没做空\"")
    doc.append("   - \"跌破1057，这段上涨纯属上去扫空单止损继续跌的\"")
    doc.append("")
    doc.append("3. **流动性被扫后的影响**")
    doc.append("   - 价格可能反转（最常见）")
    doc.append("   - 价格可能继续原方向（较少见）")
    doc.append("   - 需要重新评估市场方向")
    doc.append("")
    doc.append("4. **流动性陷阱识别**")
    doc.append("   - 周末的流动性在周一开盘前容易被扫掉")
    doc.append("   - 挂单在流动性区域附近，容易被扫")
    doc.append("   - 避免在流动性区域附近挂单")
    doc.append("")
    doc.append("**实际案例**：")
    doc.append("")
    doc.append("**案例1**：\"今天日线偏多，但考虑到早上已经扫了，周五的高点，那么接下来，要么在1075-1092这个区间震荡，或者去找106低点\"")
    doc.append("- 日线偏多（大趋势向上）")
    doc.append("- 但早上扫了周五高点（流动性被扫，可能反转）")
    doc.append("- 结果：要么区间震荡，要么下跌找前低")
    doc.append("")
    doc.append("**案例2**：\"光聊天去了，1074扫完没做空，肯定能下来的都没做空，亏一千点\"")
    doc.append("- 1074是流动性区域")
    doc.append("- 被扫后应该做空（但没做）")
    doc.append("- 结果：错过1000点利润")
    doc.append("")
    doc.append("**案例3**：\"跌破1057，这段上涨纯属上去扫空单止损继续跌的\"")
    doc.append("- 价格上涨是为了扫空单止损")
    doc.append("- 扫完后继续下跌")
    doc.append("- 这是典型的流动性陷阱")
    doc.append("")
    
    doc.append("### 2.3 情景规划（多情景分析，必须执行）")
    doc.append("")
    doc.append("**De.的核心分析方法**：考虑多种可能的市场走势")
    doc.append("")
    doc.append("**典型分析模式**：")
    doc.append("- \"要么...或者...\"")
    doc.append("- \"可能...也可能...\"")
    doc.append("- \"如果...那么...\"")
    doc.append("")
    doc.append("**情景规划步骤**：")
    doc.append("")
    doc.append("1. **列出所有可能的情景**")
    doc.append("   - 情景A：区间震荡")
    doc.append("   - 情景B：趋势延续")
    doc.append("   - 情景C：反转")
    doc.append("")
    doc.append("2. **为每个情景准备交易计划**")
    doc.append("   - 情景A的交易计划")
    doc.append("   - 情景B的交易计划")
    doc.append("   - 情景C的交易计划")
    doc.append("")
    doc.append("3. **观察市场发展，选择对应的交易计划**")
    doc.append("   - 如果市场符合情景A → 执行情景A的计划")
    doc.append("   - 如果市场符合情景B → 执行情景B的计划")
    doc.append("   - 如果市场不符合任何情景 → 等待或退出")
    doc.append("")
    doc.append("**实际案例深度分析**：")
    doc.append("")
    doc.append("**案例1**：\"今天日线偏多，但考虑到早上已经扫了，周五的高点，那么接下来，要么在1075-1092这个区间震荡，或者去找106低点\"")
    doc.append("")
    doc.append("**分析步骤**：")
    doc.append("")
    doc.append("**步骤1：趋势分析**")
    doc.append("- 日线偏多 = 大趋势向上")
    doc.append("- 这意味着长期方向是上涨")
    doc.append("")
    doc.append("**步骤2：关键事件分析**")
    doc.append("- \"早上已经扫了，周五的高点\"")
    doc.append("- 周五的高点 = 流动性区域")
    doc.append("- 被扫 = 流动性被吃掉")
    doc.append("- 影响：流动性被扫后，价格可能反转或继续原方向")
    doc.append("")
    doc.append("**步骤3：情景规划**")
    doc.append("")
    doc.append("**情景A：区间震荡（1075-1092）**")
    doc.append("- 区间：10750-10920，宽度170点")
    doc.append("- 交易策略：区间挂单交易")
    doc.append("- 多单：10750附近挂单，止损10720，止盈10900")
    doc.append("- 空单：10920附近挂单，止损10950，止盈10770")
    doc.append("- 风险：中等")
    doc.append("- 概率：较高（流动性被扫后，价格可能震荡）")
    doc.append("")
    doc.append("**情景B：趋势延续（去找106低点）**")
    doc.append("- 目标：10600（前低）")
    doc.append("- 交易策略：等待下跌，在10600附近做多")
    doc.append("- 或：如果跌破10600，做空")
    doc.append("- 风险：较高（与日线偏多相反）")
    doc.append("- 概率：较低（但需要准备）")
    doc.append("")
    doc.append("**步骤4：交易计划**")
    doc.append("1. 观察价格行为，判断是情景A还是情景B")
    doc.append("2. 如果价格在1075-1092震荡 → 执行区间交易（情景A）")
    doc.append("3. 如果价格下跌 → 等待10600附近的机会（情景B）")
    doc.append("4. 根据市场发展调整策略")
    doc.append("")
    doc.append("**案例2**：\"如果106-1074是个供给区，那价格传递的目标在等同宽度向上测量的区域派发，那就是还有一个结论在1103-1176区间震荡派发\"")
    doc.append("")
    doc.append("**分析**：")
    doc.append("- 106-1074是供给区（宽度=140点）")
    doc.append("- 如果价格向上突破，目标 = 1074 + 140 = 1214")
    doc.append("- 但实际可能在1103-1176区间震荡派发")
    doc.append("- 交易策略：在1103-1176区间做空")
    doc.append("")
    doc.append("**案例3**：\"如果按这个走，应对方法就是在1117附近加仓，在1103附近减仓，或者等去补cme缺口，11075\"")
    doc.append("")
    doc.append("**分析**：")
    doc.append("- 情景A：在1117附近加仓（继续上涨）")
    doc.append("- 情景B：在1103附近减仓（回调）")
    doc.append("- 情景C：等去补CME缺口（11075）")
    doc.append("- 为每个情景准备交易计划")
    doc.append("")
    
    doc.append("### 2.4 市场结构分析（供给区/需求区/派发/吸筹/养单）")
    doc.append("")
    doc.append("**市场结构概念**：")
    doc.append("")
    doc.append("1. **供给区（Supply Zone）**")
    doc.append("   - 定义：大量卖单集中的区域")
    doc.append("   - 特征：价格在此区域容易下跌")
    doc.append("   - 应用：在供给区附近做空")
    doc.append("   - 识别：价格快速下跌前的最后一个上涨区域")
    doc.append("")
    doc.append("2. **需求区（Demand Zone）**")
    doc.append("   - 定义：大量买单集中的区域")
    doc.append("   - 特征：价格在此区域容易上涨")
    doc.append("   - 应用：在需求区附近做多")
    doc.append("   - 识别：价格快速上涨前的最后一个下跌区域")
    doc.append("")
    doc.append("3. **派发（Distribution）**")
    doc.append("   - 定义：机构在高位派发筹码")
    doc.append("   - 特征：价格在区间内震荡，但最终会下跌")
    doc.append("   - 应用：识别派发区间，准备做空")
    doc.append("   - 识别：区间内多头总是能赚，但价格不突破，最终下跌")
    doc.append("")
    doc.append("4. **吸筹（Accumulation）**")
    doc.append("   - 定义：机构在低位收集筹码")
    doc.append("   - 特征：价格在区间内震荡，但最终会上涨")
    doc.append("   - 应用：识别吸筹区间，准备做多")
    doc.append("   - 识别：区间内空头总是能赚，但价格不跌破，最终上涨")
    doc.append("")
    doc.append("5. **养单行为（Trapping）**")
    doc.append("   - 定义：\"养空头\" 或 \"养多头\"")
    doc.append("   - 特征：价格在某个方向制造假象，然后反向运行")
    doc.append("   - 应用：识别养单行为，避免被套")
    doc.append("   - 识别：")
    doc.append("     * 养空头 = 价格先上涨，让空头加仓，然后下跌")
    doc.append("     * 养多头 = 价格先下跌，让多头加仓，然后上涨")
    doc.append("")
    doc.append("**实际案例**：")
    doc.append("")
    doc.append("**案例1**：\"目前来看，这段震荡区间跟106-1074那段区间相反，这段区间多头总是能赚，上一段区间空头总是能赚，判断106-1074是在养空头，那么这段到现在为止出现养多头行为！\"")
    doc.append("")
    doc.append("**分析**：")
    doc.append("- 106-1074区间：空头总是能赚 → 养空头（价格先上涨，然后下跌）")
    doc.append("- 当前区间：多头总是能赚 → 养多头（价格先下跌，然后上涨）")
    doc.append("- 交易策略：识别养单行为，避免被套")
    doc.append("")
    doc.append("**案例2**：\"如果106-1074是个供给区，那价格传递的目标在等同宽度向上测量的区域派发\"")
    doc.append("")
    doc.append("**分析**：")
    doc.append("- 106-1074是供给区（宽度140点）")
    doc.append("- 价格向上突破后，可能在1103-1176区间派发")
    doc.append("- 交易策略：在派发区间做空")
    doc.append("")
    
    doc.append("### 2.5 时间周期分析")
    doc.append("")
    doc.append("**时间因素的重要性**：")
    doc.append("")
    doc.append("1. **周五/周一效应**")
    doc.append("   - 周五的高点/低点可能被周一扫掉")
    doc.append("   - \"早上已经扫了，周五的高点\"")
    doc.append("   - 需要考虑周末流动性变化")
    doc.append("")
    doc.append("2. **周末流动性**")
    doc.append("   - 周末流动性不足")
    doc.append("   - 周末的流动性在周一开盘前容易被扫掉")
    doc.append("   - **规则**：周末不适合交易")
    doc.append("")
    doc.append("3. **日内时间分析**")
    doc.append("   - 早上、中午、晚上的市场行为可能不同")
    doc.append("   - 需要考虑不同时段的流动性变化")
    doc.append("")
    
    # 三、完整的交易决策流程
    doc.append("## 三、完整的交易决策流程（必须严格执行）")
    doc.append("")
    
    doc.append("### 步骤1：多维度市场分析（必须完成）")
    doc.append("")
    doc.append("**必须分析的内容**：")
    doc.append("")
    doc.append("1. **趋势分析**")
    doc.append("   □ 日线级别趋势（偏多/偏空）")
    doc.append("   □ 4小时趋势")
    doc.append("   □ 1小时趋势")
    doc.append("   □ 15分钟趋势")
    doc.append("   □ 多时间框架是否一致")
    doc.append("")
    doc.append("2. **流动性分析**（关键）")
    doc.append("   □ 最近是否有流动性被扫（高点/低点）")
    doc.append("   □ 当前流动性区域在哪里")
    doc.append("   □ 流动性被扫后的市场反应如何")
    doc.append("   □ 是否有周五/周一效应")
    doc.append("   □ 周末流动性是否充足（周末不适合交易）")
    doc.append("")
    doc.append("3. **市场结构分析**")
    doc.append("   □ 当前是供给区还是需求区")
    doc.append("   □ 是否有派发或吸筹行为")
    doc.append("   □ 是否有养单行为（养空头/养多头）")
    doc.append("   □ 市场结构是否支持当前交易方向")
    doc.append("")
    doc.append("4. **时间周期分析**")
    doc.append("   □ 确认不是周末/周六")
    doc.append("   □ 确认流动性充足的时间段")
    doc.append("   □ 考虑周五/周一效应")
    doc.append("")
    doc.append("5. **情景规划**（必须执行）")
    doc.append("   □ 列出所有可能的市场走势（至少2-3个情景）")
    doc.append("   □ 为每个情景准备了详细的交易计划")
    doc.append("   □ 确定了最可能的情景")
    doc.append("   □ 准备了应对方案（如果市场不符合任何情景）")
    doc.append("")
    
    doc.append("### 步骤2：识别交易区间")
    doc.append("")
    doc.append("**区间识别方法**：")
    doc.append("")
    doc.append("1. **观察价格实际震荡范围**")
    doc.append("   - 在图表上找到明显的价格震荡区间")
    doc.append("   - 确定区间上沿（阻力位）和下沿（支撑位）")
    doc.append("   - 区间宽度：通常100-500点")
    doc.append("")
    doc.append("2. **使用Vegas通道确认**")
    doc.append("   - 添加EMA144和EMA169")
    doc.append("   - 用Vegas通道确认区间边界")
    doc.append("   - 注意：区间 ≠ Vegas通道宽度")
    doc.append("")
    doc.append("3. **使用VWAP确认**")
    doc.append("   - 添加对应时间框架的VWAP")
    doc.append("   - VWAP在区间内 = 作为动态支撑/阻力")
    doc.append("")
    doc.append("4. **结合市场结构**")
    doc.append("   - 区间是供给区还是需求区？")
    doc.append("   - 是否有派发或吸筹行为？")
    doc.append("   - 是否有养单行为？")
    doc.append("")
    
    doc.append("### 步骤3：入场决策")
    doc.append("")
    doc.append("**入场前必须确认**：")
    doc.append("")
    doc.append("1. **趋势确认**")
    doc.append("   - 大趋势方向（日线）")
    doc.append("   - 小趋势方向（15分钟/1小时）")
    doc.append("   - 趋势是否一致（理想情况）")
    doc.append("")
    doc.append("2. **流动性确认**")
    doc.append("   - 流动性是否已被扫（如果被扫，重新评估）")
    doc.append("   - 当前流动性区域位置")
    doc.append("   - 避免在流动性区域附近挂单")
    doc.append("")
    doc.append("3. **市场结构确认**")
    doc.append("   - 是否在供给区/需求区")
    doc.append("   - 是否有养单行为（如有，需要特别小心）")
    doc.append("   - 是否有派发/吸筹行为")
    doc.append("")
    doc.append("4. **时间确认**")
    doc.append("   - 不是周末/周六（周末不适合交易）")
    doc.append("   - 流动性充足的时间段")
    doc.append("")
    doc.append("5. **入场位置**")
    doc.append("   - 区间上下沿附近挂单")
    doc.append("   - 不追价，必须挂单等待")
    doc.append("   - 挂单价格：区间上下沿±10-20点")
    doc.append("")
    
    doc.append("### 步骤4：风险管理")
    doc.append("")
    doc.append("**止损设置**：")
    doc.append("- 位置：假突破不能打到的位置")
    doc.append("- 距离：通常几百点（根据区间大小调整）")
    doc.append("- 参考：流动性区域外，不破大周期EMA")
    doc.append("- **规则**：\"找好流动性区域挂单止损一般就几百点\"")
    doc.append("")
    doc.append("**止盈设置**：")
    doc.append("- 位置：区间上下沿或中间位置")
    doc.append("- 盈亏比：至少2倍")
    doc.append("- 分批止盈：50%在目标位置，50%看情况")
    doc.append("")
    doc.append("**仓位管理**：")
    doc.append("- 风险不超过账户的5%")
    doc.append("- 使用逐仓模式")
    doc.append("- 根据止损距离计算仓位大小")
    doc.append("")
    
    # 四、完整的交易检查清单
    doc.append("## 四、完整交易检查清单（必须逐项确认）")
    doc.append("")
    doc.append("### A. 市场分析检查")
    doc.append("")
    doc.append("**趋势分析**：")
    doc.append("□ 1. 日线级别趋势（偏多/偏空）")
    doc.append("□ 2. 4小时趋势")
    doc.append("□ 3. 1小时趋势")
    doc.append("□ 4. 15分钟趋势")
    doc.append("□ 5. 多时间框架是否一致")
    doc.append("")
    doc.append("**流动性分析**（关键）：")
    doc.append("□ 6. 最近是否有流动性被扫（高点/低点）")
    doc.append("□ 7. 当前流动性区域在哪里")
    doc.append("□ 8. 流动性被扫后的市场反应如何")
    doc.append("□ 9. 是否有周五/周一效应")
    doc.append("□ 10. 周末流动性是否充足（周末不适合交易）")
    doc.append("")
    doc.append("**市场结构分析**：")
    doc.append("□ 11. 当前是供给区还是需求区")
    doc.append("□ 12. 是否有派发或吸筹行为")
    doc.append("□ 13. 是否有养单行为（养空头/养多头）")
    doc.append("□ 14. 市场结构是否支持当前交易方向")
    doc.append("")
    doc.append("**时间周期分析**：")
    doc.append("□ 15. 确认不是周末/周六")
    doc.append("□ 16. 确认流动性充足的时间段")
    doc.append("□ 17. 考虑周五/周一效应")
    doc.append("")
    doc.append("**情景规划**（必须执行）：")
    doc.append("□ 18. 列出所有可能的市场走势（至少2-3个情景）")
    doc.append("□ 19. 为每个情景准备了详细的交易计划")
    doc.append("□ 20. 确定了最可能的情景")
    doc.append("□ 21. 准备了应对方案（如果市场不符合任何情景）")
    doc.append("")
    
    doc.append("### B. 交易区间检查")
    doc.append("")
    doc.append("□ 22. 已识别明确的震荡区间（价格实际震荡范围）")
    doc.append("□ 23. 区间宽度足够（通常100-500点）")
    doc.append("□ 24. 已使用Vegas通道确认区间边界")
    doc.append("□ 25. 已使用VWAP确认支撑阻力位置")
    doc.append("□ 26. 确认区间内价格来回震荡，不是单边趋势")
    doc.append("□ 27. 已识别区间是供给区还是需求区")
    doc.append("")
    
    doc.append("### C. 入场条件检查")
    doc.append("")
    doc.append("□ 28. 价格在区间上下沿附近")
    doc.append("□ 29. 大趋势方向确认（与交易方向一致）")
    doc.append("□ 30. 流动性分析完成（未被扫或已处理）")
    doc.append("□ 31. 市场结构支持交易方向")
    doc.append("□ 32. 已挂单（不追价）")
    doc.append("□ 33. 挂单价格合理（区间上下沿±10-20点）")
    doc.append("□ 34. 确认不是周末/周六")
    doc.append("")
    
    doc.append("### D. 风险管理检查")
    doc.append("")
    doc.append("□ 35. 已设置止损（假突破不能打到）")
    doc.append("□ 36. 止损距离合理（通常几百点）")
    doc.append("□ 37. 止损在流动性区域外")
    doc.append("□ 38. 止损不破大周期EMA")
    doc.append("□ 39. 已设置止盈（2倍以上盈亏比）")
    doc.append("□ 40. 已计算仓位大小（风险不超过5%）")
    doc.append("□ 41. 已使用逐仓模式")
    doc.append("□ 42. 盈亏比≥2倍")
    doc.append("")
    
    doc.append("### E. 特殊情况检查")
    doc.append("")
    doc.append("□ 43. 已考虑流动性被扫的情况")
    doc.append("□ 44. 已识别市场结构（供给区/需求区）")
    doc.append("□ 45. 已识别养单行为（如有）")
    doc.append("□ 46. 已准备多情景交易计划")
    doc.append("□ 47. 确认不是单边行情")
    doc.append("")
    doc.append("")
    doc.append("**只有所有47项都确认后，才能执行交易！**")
    doc.append("")
    
    # 五、结合成熟交易系统理论
    doc.append("## 五、结合成熟交易系统理论")
    doc.append("")
    
    doc.append("### 5.1 ICT（Inner Circle Trader）概念")
    doc.append("")
    doc.append("De.的系统融合了ICT交易理论：")
    doc.append("")
    doc.append("1. **FVG（Fair Value Gap）**")
    doc.append("   - 价格跳空形成的价值缺口")
    doc.append("   - 价格回填FVG时是交易机会")
    doc.append("   - 应用：\"回补四小时fvg后，来个大阴线\"")
    doc.append("")
    doc.append("2. **Order Block（OB）**")
    doc.append("   - 机构订单区域")
    doc.append("   - 价格回到OB时是交易机会")
    doc.append("")
    doc.append("3. **OTE区间（Optimal Trade Entry）**")
    doc.append("   - 618-786斐波那契回撤区间")
    doc.append("   - 突破后回踩到OTE区间是入场机会")
    doc.append("   - 应用：\"618-786区间是ict老头的ote区间，这个区间胜率盈亏都很好的\"")
    doc.append("")
    doc.append("4. **流动性（Liquidity）**")
    doc.append("   - 大量挂单的位置")
    doc.append("   - 流动性被扫后，价格可能反转")
    doc.append("   - 应用：\"早上已经扫了，周五的高点\"")
    doc.append("")
    
    doc.append("### 5.2 市场微观结构理论")
    doc.append("")
    doc.append("1. **供给与需求**")
    doc.append("   - 供给区 = 大量卖单")
    doc.append("   - 需求区 = 大量买单")
    doc.append("   - 价格在供给区下跌，在需求区上涨")
    doc.append("")
    doc.append("2. **派发与吸筹**")
    doc.append("   - 派发 = 机构在高位卖出")
    doc.append("   - 吸筹 = 机构在低位买入")
    doc.append("   - 识别派发/吸筹区间，预测价格方向")
    doc.append("")
    doc.append("3. **市场操纵**")
    doc.append("   - 养单行为 = 制造假象，然后反向运行")
    doc.append("   - 识别养单行为，避免被套")
    doc.append("")
    
    doc.append("### 5.3 价格行为交易")
    doc.append("")
    doc.append("1. **支撑阻力**")
    doc.append("   - 使用Vegas通道识别")
    doc.append("   - 使用VWAP确认")
    doc.append("   - 结合流动性区域")
    doc.append("")
    doc.append("2. **价格形态**")
    doc.append("   - M顶/W底")
    doc.append("   - 回踩确认")
    doc.append("   - 假突破识别")
    doc.append("")
    
    # 六、总结
    doc.append("## 六、系统总结")
    doc.append("")
    doc.append("### 核心原则")
    doc.append("")
    doc.append("1. **多维度分析**：趋势 + 流动性 + 市场结构 + 时间周期")
    doc.append("2. **多情景规划**：考虑所有可能的市场走势，为每个情景准备交易计划")
    doc.append("3. **严格风险管理**：止损 + 止盈 + 仓位管理 + 盈亏比≥2倍")
    doc.append("4. **流动性优先**：关注流动性被扫的情况，流动性被扫后重新评估市场")
    doc.append("5. **市场结构识别**：供给区/需求区/派发/吸筹/养单")
    doc.append("6. **时间周期考虑**：避免周末交易，考虑周五/周一效应")
    doc.append("")
    doc.append("### 交易前必须完成")
    doc.append("")
    doc.append("1. 完整的市场分析（47项检查清单）")
    doc.append("2. 多情景交易计划（至少2-3个情景）")
    doc.append("3. 风险控制设置（止损、止盈、仓位）")
    doc.append("4. 特殊情况处理方案（流动性被扫、养单行为等）")
    doc.append("")
    doc.append("**只有完成所有检查后，才能执行交易！**")
    doc.append("")
    doc.append("---")
    doc.append("")
    doc.append("**文档版本**: 最终增强版")
    doc.append("**最后更新**: 2025年")
    doc.append("**基于**: De.的所有实际交易记录和规则总结")
    doc.append("")
    
    return "\n".join(doc)

def main():
    output_file = "De_trading_system_final_enhanced.md"
    system_doc = generate_enhanced_system()
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(system_doc)
    
    print("=" * 80)
    print("完成！")
    print("=" * 80)
    print(f"最终增强版交易系统已保存到: {output_file}")
    print()
    print("主要特点：")
    print("  1. 多维度市场分析（趋势+流动性+市场结构+时间）")
    print("  2. 多情景规划（考虑所有可能的市场走势）")
    print("  3. 完整的47项检查清单")
    print("  4. 结合ICT和市场微观结构理论")
    print("  5. 深度案例分析")
    print("  6. 流动性分析详细说明")
    print("  7. 市场结构识别（供给区/需求区/派发/吸筹/养单）")

if __name__ == "__main__":
    main()




