#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
View Recent Trading Signals
Quick script to check signals generated by continuous scanner
"""

import argparse
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from db_manager_trader import TraderDBManager


def _parse_dt(value: object) -> Optional[datetime]:
    if isinstance(value, datetime):
        return value
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M", "%Y-%m-%d"):
        try:
            return datetime.strptime(text, fmt)
        except Exception:
            continue
    try:
        return datetime.fromisoformat(text)
    except Exception:
        return None


def format_signal(signal: dict) -> str:
    """Format a signal for display"""
    lines = []
    lines.append("=" * 70)
    lines.append(f"Symbol: {signal.get('symbol', 'N/A')}")
    lines.append(f"Time: {signal.get('signal_time', 'N/A')}")
    lines.append(f"Timeframe: {signal.get('timeframe', 'N/A')}")
    lines.append(f"Entry: {signal.get('entry_price', 'N/A')}")
    lines.append(f"Stop Loss: {signal.get('stop_loss', 'N/A')}")
    lines.append(
        f"TP1: {signal.get('take_profit_1', 'N/A')} | TP2: {signal.get('take_profit_2', 'N/A')}"
    )
    lines.append(f"Score: {signal.get('score', 'N/A')}")
    lines.append(f"Status: {signal.get('status', 'N/A')}")

    notes = signal.get("notes", "")
    if notes:
        lines.append(f"Notes: {notes[:100]}...")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="View recent trading signals")
    parser.add_argument(
        "--hours",
        type=int,
        default=24,
        help="Show signals from last N hours (default: 24)",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=20,
        help="Maximum number of signals to show (default: 20)",
    )
    parser.add_argument(
        "--timeframe", type=str, default=None, help="Filter by timeframe (5m, 15m, 1h)"
    )
    parser.add_argument(
        "--symbol", type=str, default=None, help="Filter by symbol (e.g., BTCUSDT)"
    )

    args = parser.parse_args()

    # Initialize database manager
    db = TraderDBManager("abu")

    # Calculate time range
    since_time = datetime.now() - timedelta(hours=args.hours)

    print(f"\n{'=' * 70}")
    print(f"TRADING SIGNALS - Last {args.hours} hours")
    print(f"{'=' * 70}\n")

    try:
        days = max(1, int(args.hours // 24) + 1)
        signals = db.get_trading_signals(
            timeframe=args.timeframe,
            symbol=args.symbol.upper() if args.symbol else None,
            system_name="abu",
            limit=args.limit,
            days=days,
        )
        signals = [
            s
            for s in signals
            if (_parse_dt(s.get("signal_time")) or _parse_dt(s.get("created_at")))
            and (_parse_dt(s.get("signal_time")) or _parse_dt(s.get("created_at")))
            >= since_time
        ]

        if not signals:
            print("No signals found in the specified time range.")
            print(f"Time range: {since_time.strftime('%Y-%m-%d %H:%M:%S')} to now")
            return

        print(f"Found {len(signals)} signal(s)\n")

        for i, signal in enumerate(signals, 1):
            print(f"\nSignal #{i}")
            print(format_signal(signal))

        print(f"\n{'=' * 70}")
        print(f"Total: {len(signals)} signal(s)")
        print(f"{'=' * 70}\n")

    except Exception as e:
        print(f"Error querying signals: {e}")
        import traceback

        traceback.print_exc()


if __name__ == "__main__":
    main()
