#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
信号通知优化方案
针对早上9点信号未接到挂单的问题，提供优化建议和实现
"""

import sys
from pathlib import Path
from datetime import datetime

# 设置UTF-8编码
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

# 添加src目录到路径
current_dir = Path(__file__).parent
if str(current_dir) not in sys.path:
    sys.path.insert(0, str(current_dir))


def generate_optimization_plan():
    """生成优化方案文档"""
    
    plan = []
    plan.append("# 信号通知优化方案")
    plan.append("")
    plan.append(f"**生成时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    plan.append("")
    plan.append("## 问题分析")
    plan.append("")
    plan.append("### 现状问题")
    plan.append("")
    plan.append("1. **信号生成时间**: 早上9点附近生成15分钟做多信号")
    plan.append("2. **入场价**: $87,702")
    plan.append("3. **问题**: 信号生成后未及时接到挂单，错过交易机会")
    plan.append("")
    plan.append("### 根本原因")
    plan.append("")
    plan.append("1. **检查频率低**: 系统每4小时才运行一次，可能错过价格接近入场价的时机")
    plan.append("2. **无实时监控**: 信号生成后，没有实时监控价格变化")
    plan.append("3. **无主动通知**: 价格接近入场价时，没有主动提醒机制")
    plan.append("4. **无优先级区分**: 强信号和弱信号没有区别对待")
    plan.append("")
    plan.append("## 优化方案")
    plan.append("")
    plan.append("### 方案1: 实时价格监控（推荐）")
    plan.append("")
    plan.append("**实现**: `src/signal_monitor.py`")
    plan.append("")
    plan.append("**功能**:")
    plan.append("- 每15分钟检查一次所有pending信号")
    plan.append("- 当价格距离入场价3%时，发送警告提醒")
    plan.append("- 当价格距离入场价1.5%时，发送强烈提醒")
    plan.append("- 当价格距离入场价1%时，标记为可入场并立即通知")
    plan.append("")
    plan.append("**使用方法**:")
    plan.append("```bash")
    plan.append("# 持续监控（每15分钟检查一次）")
    plan.append("python src/signal_monitor.py")
    plan.append("")
    plan.append("# 只检查一次")
    plan.append("python src/signal_monitor.py --once")
    plan.append("")
    plan.append("# 自定义检查间隔（每5分钟检查一次）")
    plan.append("python src/signal_monitor.py --interval 300")
    plan.append("```")
    plan.append("")
    plan.append("### 方案2: 信号生成时立即通知")
    plan.append("")
    plan.append("**实现位置**: `src/unified_trading_system.py`")
    plan.append("")
    plan.append("**优化点**:")
    plan.append("1. 信号生成后，立即检查当前价格与入场价的距离")
    plan.append("2. 如果距离<3%，立即生成通知文件")
    plan.append("3. 强信号（strength='strong'）无论距离如何都生成提醒")
    plan.append("")
    plan.append("### 方案3: 定时任务集成")
    plan.append("")
    plan.append("**实现**: 在Windows任务计划程序中添加定时任务")
    plan.append("")
    plan.append("**配置**:")
    plan.append("- 每15分钟运行一次: `python src/signal_monitor.py --once`")
    plan.append("- 在系统启动时启动持续监控: `python src/signal_monitor.py`")
    plan.append("")
    plan.append("### 方案4: 增强通知机制（未来扩展）")
    plan.append("")
    plan.append("**可选功能**:")
    plan.append("1. **邮件通知**: 价格接近时发送邮件")
    plan.append("2. **微信通知**: 集成企业微信或微信机器人")
    plan.append("3. **短信通知**: 紧急信号发送短信")
    plan.append("4. **桌面通知**: Windows桌面弹窗提醒")
    plan.append("")
    plan.append("## 实施步骤")
    plan.append("")
    plan.append("### 立即实施（推荐）")
    plan.append("")
    plan.append("1. ✅ **已创建**: `src/signal_monitor.py` - 实时监控模块")
    plan.append("2. 🔄 **需要修改**: `src/unified_trading_system.py` - 信号生成时立即检查")
    plan.append("3. 🔄 **需要配置**: Windows任务计划程序 - 每15分钟运行监控")
    plan.append("")
    plan.append("### 修改 `unified_trading_system.py`")
    plan.append("")
    plan.append("在 `_extract_and_track_de_signals` 方法中添加：")
    plan.append("")
    plan.append("```python")
    plan.append("# 信号生成后立即检查价格接近度")
    plan.append("if self.signal_tracker and current_price:")
    plan.append("    from signal_monitor import SignalMonitor")
    plan.append("    monitor = SignalMonitor()")
    plan.append("    # 只检查新生成的信号")
    plan.append("    for signal_id in new_signal_ids:")
    plan.append("        signal = self.signal_tracker.get_signal_by_id(signal_id)")
    plan.append("        if signal:")
    plan.append("            proximity = monitor.check_signal_proximity(signal, current_price)")
    plan.append("            if proximity['status'] in ['warning', 'alert', 'ready']:")
    plan.append("                # 立即生成通知")
    plan.append("                notification = monitor.format_signal_notification(signal, proximity, current_price)")
    plan.append("                monitor.save_notifications([notification])")
    plan.append("```")
    plan.append("")
    plan.append("### 配置定时任务")
    plan.append("")
    plan.append("**Windows任务计划程序**:")
    plan.append("")
    plan.append("1. 打开\"任务计划程序\"")
    plan.append("2. 创建基本任务")
    plan.append("3. 触发器: 每15分钟")
    plan.append("4. 操作: 启动程序")
    plan.append("5. 程序: `python`")
    plan.append("6. 参数: `src/signal_monitor.py --once`")
    plan.append("7. 起始于: 项目目录路径")
    plan.append("")
    plan.append("## 使用建议")
    plan.append("")
    plan.append("### 日常使用")
    plan.append("")
    plan.append("1. **启动监控**: 在交易时段启动持续监控")
    plan.append("   ```bash")
    plan.append("   python src/signal_monitor.py")
    plan.append("   ```")
    plan.append("")
    plan.append("2. **查看通知**: 检查 `trading_signals/信号提醒_*.md` 文件")
    plan.append("")
    plan.append("3. **手动检查**: 需要时手动运行一次检查")
    plan.append("   ```bash")
    plan.append("   python src/signal_monitor.py --once")
    plan.append("   ```")
    plan.append("")
    plan.append("### 针对早上9点信号的特殊处理")
    plan.append("")
    plan.append("1. **提前准备**: 在早上8:45启动监控")
    plan.append("2. **缩短间隔**: 早上9-10点期间，使用5分钟检查间隔")
    plan.append("   ```bash")
    plan.append("   python src/signal_monitor.py --interval 300")
    plan.append("   ```")
    plan.append("3. **重点关注**: 强信号（strength='strong'）会优先通知")
    plan.append("")
    plan.append("## 预期效果")
    plan.append("")
    plan.append("1. ✅ **及时通知**: 价格接近入场价时立即收到提醒")
    plan.append("2. ✅ **不错过机会**: 15分钟检查间隔确保不错过价格接近的时机")
    plan.append("3. ✅ **优先级区分**: 强信号优先通知")
    plan.append("4. ✅ **历史记录**: 所有通知保存到文件，便于回顾")
    plan.append("")
    plan.append("## 注意事项")
    plan.append("")
    plan.append("1. ⚠️  监控系统需要持续运行，建议使用任务计划程序")
    plan.append("2. ⚠️  检查间隔不要设置太短（建议≥5分钟），避免过度请求API")
    plan.append("3. ⚠️  通知文件会累积，建议定期清理旧文件")
    plan.append("")
    
    return "\n".join(plan)


def main():
    """主函数"""
    base_dir = Path(__file__).parent.parent
    output_dir = base_dir / "trading_signals"
    output_dir.mkdir(exist_ok=True)
    
    plan_content = generate_optimization_plan()
    
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    plan_file = output_dir / f"信号通知优化方案_{timestamp}.md"
    
    plan_file.write_text(plan_content, encoding='utf-8')
    
    print("=" * 80)
    print("信号通知优化方案已生成")
    print("=" * 80)
    print(f"文件: {plan_file.name}")
    print()
    print("主要优化措施:")
    print("1. ✅ 创建实时监控模块 (src/signal_monitor.py)")
    print("2. 🔄 修改统一系统，信号生成时立即检查")
    print("3. 🔄 配置定时任务，每15分钟检查一次")
    print()
    print("立即使用:")
    print("  python src/signal_monitor.py --once")
    print("=" * 80)


if __name__ == "__main__":
    main()

