#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
更新De.交易系统：头寸止损设置规则
"""

import sys

def generate_stop_loss_update():
    """生成止损设置规则更新"""
    
    content = []
    content.append("## 十二、头寸止损设置规则（2025年12月24日更新）")
    content.append("")
    content.append("### 12.1 核心理念")
    content.append("")
    content.append("**De.的止损原则**: \"头寸接到就要设置止损，必须设置\"")
    content.append("")
    content.append("**核心原理**:")
    content.append("- ✅ **头寸接到就要设置止损**：每个头寸都必须立即设置止损")
    content.append("- ✅ **一比归一比**：每个头寸独立设置止损，不合并")
    content.append("- ✅ **关键区间可能反转**：在关键区间可能反转，所以必须设置止损")
    content.append("")
    content.append("### 12.2 止损设置规则")
    content.append("")
    content.append("#### 规则1：头寸接到就要设置止损")
    content.append("")
    content.append("**De.的原话**: \"头寸接到就要设置止损吗？必须设置\"")
    content.append("")
    content.append("**核心原理**:")
    content.append("- 每个头寸接到后，必须立即设置止损")
    content.append("- 不能等到价格不利时才设置止损")
    content.append("- 止损是风险控制的第一道防线")
    content.append("")
    content.append("**交易指导**:")
    content.append("1. **接到头寸后立即设置止损**:")
    content.append("   - 不要等待，不要犹豫")
    content.append("   - 立即设置止损，保护资金")
    content.append("")
    content.append("2. **止损位置**:")
    content.append("   - 根据头寸位置设置止损")
    content.append("   - 止损放在关键位下方2-3%")
    content.append("")
    content.append("#### 规则2：一比归一比（独立止损）")
    content.append("")
    content.append("**De.的原话**: \"一比归一比\"")
    content.append("")
    content.append("**核心原理**:")
    content.append("- 每个头寸独立设置止损，不合并")
    content.append("- 不同位置的头寸，止损位置不同")
    content.append("- 不能用一个止损覆盖多个头寸")
    content.append("")
    content.append("**交易指导**:")
    content.append("1. **独立止损**:")
    content.append("   - 每个头寸都有自己的止损")
    content.append("   - 不能用一个止损覆盖多个头寸")
    content.append("")
    content.append("2. **不同位置，不同止损**:")
    content.append("   - 866的头寸，止损在858下面")
    content.append("   - 860的头寸，止损在854下面")
    content.append("   - 858的头寸，止损在850下面")
    content.append("")
    content.append("#### 规则3：关键区间止损设置")
    content.append("")
    content.append("**De.的原话**: \"你那知道在这些关键的区间那比就反转了\"")
    content.append("")
    content.append("**核心原理**:")
    content.append("- 关键区间（如FVG、支撑、阻力）可能反转")
    content.append("- 在这些关键区间，必须设置止损")
    content.append("- 不能因为'可能反转'就不设置止损")
    content.append("")
    content.append("**交易指导**:")
    content.append("1. **关键区间必须设置止损**:")
    content.append("   - FVG区间、支撑区间、阻力区间")
    content.append("   - 这些区间可能反转，必须设置止损")
    content.append("")
    content.append("2. **止损位置**:")
    content.append("   - 止损放在关键区间下方2-3%")
    content.append("   - 如果价格跌破关键区间，及时止损")
    content.append("")
    content.append("### 12.3 实战案例：FVG区间分批建仓止损设置")
    content.append("")
    content.append("**案例**: FVG区间858-866分批建仓")
    content.append("")
    content.append("**情况**:")
    content.append("- FVG区间：858-866")
    content.append("- 分三次建仓：866、860、858")
    content.append("")
    content.append("**De.的止损设置**:")
    content.append("")
    content.append("1. **第一次建仓（866）**:")
    content.append("   - 头寸位置：866（FVG区间上沿）")
    content.append("   - 止损位置：858下面（FVG区间下沿下方）")
    content.append("   - 止损距离：约8点（约1%）")
    content.append("")
    content.append("2. **第二次建仓（860）**:")
    content.append("   - 头寸位置：860（FVG区间中位）")
    content.append("   - 止损位置：854下面（FVG区间下方）")
    content.append("   - 止损距离：约6点（约0.7%）")
    content.append("")
    content.append("3. **第三次建仓（858）**:")
    content.append("   - 头寸位置：858（FVG区间下沿）")
    content.append("   - 止损位置：850下面（FVG区间下方）")
    content.append("   - 止损距离：约8点（约1%）")
    content.append("")
    content.append("**关键点**:")
    content.append("- ✅ 每个头寸独立设置止损（一比归一比）")
    content.append("- ✅ 不同位置的头寸，止损位置不同")
    content.append("- ✅ 所有止损都放在FVG区间下方")
    content.append("- ✅ 如果价格跌破FVG区间，所有头寸都会被止损")
    content.append("")
    content.append("### 12.4 止损设置原则")
    content.append("")
    content.append("**原则1：立即设置**")
    content.append("- 头寸接到后立即设置止损")
    content.append("- 不要等待，不要犹豫")
    content.append("")
    content.append("**原则2：独立止损**")
    content.append("- 每个头寸独立设置止损")
    content.append("- 不同位置的头寸，止损位置不同")
    content.append("")
    content.append("**原则3：关键位下方**")
    content.append("- 止损放在关键位下方2-3%")
    content.append("- 如果价格跌破关键位，及时止损")
    content.append("")
    content.append("**原则4：风险可控**")
    content.append("- 每个头寸的止损距离要合理")
    content.append("- 确保风险可控")
    content.append("")
    content.append("### 12.5 止损设置检查清单")
    content.append("")
    content.append("**头寸接到后**:")
    content.append("□ 是否立即设置了止损？（必须设置）")
    content.append("□ 止损位置是否合理？（关键位下方2-3%）")
    content.append("□ 止损距离是否合理？（风险可控）")
    content.append("")
    content.append("**分批建仓时**:")
    content.append("□ 每个头寸是否独立设置止损？（一比归一比）")
    content.append("□ 不同位置的头寸，止损位置是否不同？")
    content.append("□ 所有止损是否都放在关键区间下方？")
    content.append("")
    content.append("**关键区间**:")
    content.append("□ 是否识别了关键区间？（FVG、支撑、阻力）")
    content.append("□ 是否设置了止损？（关键区间可能反转）")
    content.append("□ 止损是否放在关键区间下方？")
    content.append("")
    content.append("### 12.6 重要提醒")
    content.append("")
    content.append("1. **必须设置止损**：头寸接到就要设置止损，不能等待")
    content.append("2. **一比归一比**：每个头寸独立设置止损，不合并")
    content.append("3. **不同位置，不同止损**：不同位置的头寸，止损位置不同")
    content.append("4. **关键区间可能反转**：在关键区间必须设置止损")
    content.append("5. **风险可控**：每个头寸的止损距离要合理，确保风险可控")
    content.append("")
    content.append("---")
    content.append("")
    
    return "\n".join(content)

if __name__ == '__main__':
    content = generate_stop_loss_update()
    try:
        print(content)
    except UnicodeEncodeError:
        pass
    
    # 保存到文件
    with open('De_stop_loss_rules.md', 'w', encoding='utf-8') as f:
        f.write(content)
    print("\n止损设置规则已保存到: De_stop_loss_rules.md", file=sys.stderr)

