#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
更新De.交易系统：逐仓管理和反转加仓策略
"""

import sys

def generate_isolated_margin_update():
    """生成逐仓管理更新"""
    
    content = []
    content.append("## 十三、逐仓管理和反转加仓策略（2025年12月24日更新）")
    content.append("")
    content.append("### 13.1 核心理念")
    content.append("")
    content.append("**De.的逐仓原则**: \"我的每一单都是逐仓\"")
    content.append("")
    content.append("**核心原理**:")
    content.append("- ✅ **每一单都是逐仓**：每个头寸都使用逐仓模式（isolated margin）")
    content.append("- ✅ **风险隔离**：每个头寸的风险独立，不会影响其他头寸")
    content.append("- ✅ **反转加仓**：如果价格反转成功，可以把之前没打到的位置的仓位加进去")
    content.append("")
    content.append("### 13.2 逐仓管理规则")
    content.append("")
    content.append("#### 规则1：每一单都是逐仓")
    content.append("")
    content.append("**De.的原话**: \"我的每一单都是逐仓\"")
    content.append("")
    content.append("**核心原理**:")
    content.append("- 每个头寸都使用逐仓模式（isolated margin）")
    content.append("- 每个头寸的风险独立，不会影响其他头寸")
    content.append("- 这是风险管理的基础")
    content.append("")
    content.append("**逐仓 vs 全仓**:")
    content.append("")
    content.append("**逐仓（Isolated Margin）**:")
    content.append("- ✅ 每个头寸的风险独立")
    content.append("- ✅ 一个头寸爆仓，不影响其他头寸")
    content.append("- ✅ 风险可控，不会归零")
    content.append("- ✅ De.推荐使用逐仓")
    content.append("")
    content.append("**全仓（Cross Margin）**:")
    content.append("- ❌ 所有头寸共享保证金")
    content.append("- ❌ 一个头寸爆仓，可能影响其他头寸")
    content.append("- ❌ 风险不可控，可能归零")
    content.append("- ❌ De.不推荐使用全仓")
    content.append("")
    content.append("**交易指导**:")
    content.append("1. **必须使用逐仓**:")
    content.append("   - 每个头寸都设置为逐仓模式")
    content.append("   - 不要使用全仓模式")
    content.append("")
    content.append("2. **风险隔离**:")
    content.append("   - 每个头寸的风险独立")
    content.append("   - 一个头寸爆仓，不影响其他头寸")
    content.append("")
    content.append("#### 规则2：反转加仓策略")
    content.append("")
    content.append("**De.的原话**: \"比如86到了就反转了，可能前面的也止损了，反转成功了，就把之前没打到的位置的仓位，加进去\"")
    content.append("")
    content.append("**核心原理**:")
    content.append("- 如果价格在某个位置（如860）反转了")
    content.append("- 可能前面的头寸也止损了")
    content.append("- 如果反转成功了，就把之前没打到的位置的仓位加进去")
    content.append("")
    content.append("**交易指导**:")
    content.append("1. **反转确认**:")
    content.append("   - 价格在关键位置（如860）反转")
    content.append("   - 出现反转信号（下影线、锤子线等）")
    content.append("   - 确认反转成功")
    content.append("")
    content.append("2. **加仓策略**:")
    content.append("   - 如果反转成功，可以把之前没打到的位置的仓位加进去")
    content.append("   - 例如：之前计划在866、860、858建仓")
    content.append("   - 如果860反转成功，可以把866的仓位加进去（如果866没打到）")
    content.append("")
    content.append("3. **风险控制**:")
    content.append("   - 每个加仓都使用逐仓模式")
    content.append("   - 每个加仓都独立设置止损")
    content.append("")
    content.append("### 13.3 实战案例：反转加仓")
    content.append("")
    content.append("**案例**: FVG区间分批建仓 + 反转加仓")
    content.append("")
    content.append("**情况**:")
    content.append("- FVG区间：858-866")
    content.append("- 计划分三次建仓：866、860、858")
    content.append("- 价格先跌到860，然后反转")
    content.append("")
    content.append("**De.的策略**:")
    content.append("1. **第一次建仓（866）**:")
    content.append("   - 价格没到866，没建仓")
    content.append("   - 止损：858下面")
    content.append("")
    content.append("2. **第二次建仓（860）**:")
    content.append("   - 价格到860，建仓")
    content.append("   - 止损：854下面")
    content.append("   - 价格在860反转成功")
    content.append("")
    content.append("3. **反转加仓**:")
    content.append("   - 价格在860反转成功")
    content.append("   - 把之前没打到的866的仓位加进去")
    content.append("   - 在860附近加仓（相当于866的仓位）")
    content.append("   - 止损：858下面（与866的止损相同）")
    content.append("")
    content.append("**关键点**:")
    content.append("- ✅ 每个头寸都使用逐仓模式")
    content.append("- ✅ 如果反转成功，可以把之前没打到的位置的仓位加进去")
    content.append("- ✅ 每个加仓都独立设置止损")
    content.append("")
    content.append("### 13.4 逐仓管理检查清单")
    content.append("")
    content.append("**头寸设置**:")
    content.append("□ 每个头寸是否设置为逐仓模式？（必须逐仓）")
    content.append("□ 是否避免使用全仓模式？（全仓风险大）")
    content.append("□ 每个头寸的风险是否独立？")
    content.append("")
    content.append("**反转加仓**:")
    content.append("□ 价格是否在关键位置反转？")
    content.append("□ 反转是否成功？（出现反转信号）")
    content.append("□ 是否把之前没打到的位置的仓位加进去？")
    content.append("□ 每个加仓是否使用逐仓模式？")
    content.append("□ 每个加仓是否独立设置止损？")
    content.append("")
    content.append("### 13.5 重要提醒")
    content.append("")
    content.append("1. **必须使用逐仓**：每一单都是逐仓，风险隔离")
    content.append("2. **避免全仓**：全仓模式风险大，可能归零")
    content.append("3. **反转加仓**：如果反转成功，可以把之前没打到的位置的仓位加进去")
    content.append("4. **独立止损**：每个加仓都独立设置止损")
    content.append("5. **风险可控**：逐仓模式确保风险可控，不会归零")
    content.append("")
    content.append("---")
    content.append("")
    
    return "\n".join(content)

if __name__ == '__main__':
    content = generate_isolated_margin_update()
    try:
        print(content)
    except UnicodeEncodeError:
        pass
    
    # 保存到文件
    with open('De_isolated_margin_rules.md', 'w', encoding='utf-8') as f:
        f.write(content)
    print("\n逐仓管理规则已保存到: De_isolated_margin_rules.md", file=sys.stderr)




