#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
更新De.交易系统：头寸管理和加仓策略
"""

import sys

def generate_position_management_update():
    """生成头寸管理更新"""
    
    content = []
    content.append("## 十一、头寸管理和加仓策略（2025年12月24日更新）")
    content.append("")
    content.append("### 11.1 核心理念")
    content.append("")
    content.append("**De.的头寸管理原则**:")
    content.append("- ✅ **止损后继续进头寸或反手**：止损不是结束，而是新的开始")
    content.append("- ✅ **加仓在盈利后**：盈利后出现反转信号时加仓")
    content.append("- ✅ **区间分批建仓**：在关键区间内分多次建仓")
    content.append("")
    content.append("### 11.2 头寸管理规则")
    content.append("")
    content.append("#### 规则1：止损后继续进头寸或反手")
    content.append("")
    content.append("**De.的原话**: \"头寸，后面止损继续进头寸或者反手\"")
    content.append("")
    content.append("**核心原理**:")
    content.append("- 止损不是交易的结束，而是新的开始")
    content.append("- 如果止损后市场继续原方向，可以继续进头寸")
    content.append("- 如果止损后市场反转，可以反手做相反方向")
    content.append("")
    content.append("**交易指导**:")
    content.append("1. **止损后评估市场**:")
    content.append("   - 如果价格继续原方向，可以继续进头寸（追单）")
    content.append("   - 如果价格反转，可以反手做相反方向")
    content.append("")
    content.append("2. **继续进头寸的条件**:")
    content.append("   - 止损后价格继续原方向")
    content.append("   - 有明确的信号支持继续原方向")
    content.append("   - 风险可控")
    content.append("")
    content.append("3. **反手的条件**:")
    content.append("   - 止损后价格反转")
    content.append("   - 有明确的反转信号")
    content.append("   - 风险可控")
    content.append("")
    content.append("#### 规则2：加仓在盈利后")
    content.append("")
    content.append("**De.的原话**: \"加仓在盈利后面反转信号加\"")
    content.append("")
    content.append("**核心原理**:")
    content.append("- 加仓必须在盈利的基础上进行")
    content.append("- 盈利后出现反转信号时加仓（逆势加仓）")
    content.append("- 或者在一个区间内分批建仓")
    content.append("")
    content.append("**交易指导**:")
    content.append("1. **盈利后加仓**:")
    content.append("   - 第一笔单子已经盈利")
    content.append("   - 价格回调到关键位置（反转信号）")
    content.append("   - 在回调位置加仓")
    content.append("")
    content.append("2. **反转信号加仓**:")
    content.append("   - 盈利后价格回调")
    content.append("   - 回调到支撑位/阻力位（反转信号）")
    content.append("   - 在反转信号位置加仓")
    content.append("")
    content.append("3. **区间分批建仓**:")
    content.append("   - 在一个关键区间内分多次建仓")
    content.append("   - 例如：FVG区间、支撑区间、阻力区间")
    content.append("")
    content.append("#### 规则3：区间分批建仓")
    content.append("")
    content.append("**De.的原话**: \"比如今天说的我858-866这个fvg区间分三次进，866-86-858，进去，止损851下方\"")
    content.append("")
    content.append("**核心原理**:")
    content.append("- 在关键区间内分多次建仓，降低平均成本")
    content.append("- 每次建仓都在区间的不同位置")
    content.append("- 统一止损放在区间下方")
    content.append("")
    content.append("**实战案例**: FVG区间分批建仓")
    content.append("")
    content.append("**情况**:")
    content.append("- FVG区间：858-866")
    content.append("- 分三次建仓：866、860、858")
    content.append("- 统一止损：851下方")
    content.append("")
    content.append("**De.的策略**:")
    content.append("1. **第一次建仓**：866（FVG区间上沿）")
    content.append("2. **第二次建仓**：860（FVG区间中位）")
    content.append("3. **第三次建仓**：858（FVG区间下沿）")
    content.append("4. **统一止损**：851下方（FVG区间下方2-3%）")
    content.append("")
    content.append("**优势**:")
    content.append("- 降低平均成本")
    content.append("- 如果价格在区间内反弹，可以吃到利润")
    content.append("- 如果价格跌破区间，统一止损，风险可控")
    content.append("")
    content.append("### 11.3 加仓策略详解")
    content.append("")
    content.append("#### 策略1：盈利后反转信号加仓")
    content.append("")
    content.append("**适用场景**:")
    content.append("- 第一笔单子已经盈利")
    content.append("- 价格回调到关键位置")
    content.append("- 出现反转信号（支撑/阻力）")
    content.append("")
    content.append("**交易步骤**:")
    content.append("1. 第一笔单子盈利后，移动止损到保本")
    content.append("2. 价格回调到关键位置（如支撑位、Vegas通道）")
    content.append("3. 出现反转信号（下影线、锤子线等）")
    content.append("4. 在反转信号位置加仓")
    content.append("5. 止损放在关键位下方")
    content.append("")
    content.append("**示例**:")
    content.append("- 第一笔：88000做多，盈利到88300，移动止损到88000（保本）")
    content.append("- 价格回调到87800（Vegas通道），出现下影线（反转信号）")
    content.append("- 在87800加仓，止损放在87500（Vegas通道下方）")
    content.append("")
    content.append("#### 策略2：区间分批建仓")
    content.append("")
    content.append("**适用场景**:")
    content.append("- FVG区间")
    content.append("- 支撑区间")
    content.append("- 阻力区间")
    content.append("- 震荡区间")
    content.append("")
    content.append("**交易步骤**:")
    content.append("1. 识别关键区间（如FVG、支撑、阻力）")
    content.append("2. 在区间内分3-5次建仓")
    content.append("3. 每次建仓在区间的不同位置")
    content.append("4. 统一止损放在区间下方2-3%")
    content.append("")
    content.append("**示例**: FVG区间分批建仓")
    content.append("- FVG区间：858-866")
    content.append("- 第一次：866（上沿）")
    content.append("- 第二次：860（中位）")
    content.append("- 第三次：858（下沿）")
    content.append("- 统一止损：851下方")
    content.append("")
    content.append("### 11.4 头寸管理检查清单")
    content.append("")
    content.append("**止损后处理**:")
    content.append("□ 止损后是否评估市场方向？")
    content.append("□ 如果继续原方向，是否继续进头寸？")
    content.append("□ 如果反转，是否反手？")
    content.append("")
    content.append("**加仓前检查**:")
    content.append("□ 第一笔单子是否已经盈利？")
    content.append("□ 是否出现反转信号？")
    content.append("□ 是否在关键位置（支撑/阻力）？")
    content.append("□ 风险是否可控？")
    content.append("")
    content.append("**区间分批建仓检查**:")
    content.append("□ 是否识别了关键区间？")
    content.append("□ 是否规划了分批建仓位置？")
    content.append("□ 是否设置了统一止损？")
    content.append("□ 平均成本是否合理？")
    content.append("")
    content.append("### 11.5 重要提醒")
    content.append("")
    content.append("1. **止损不是结束**：止损后可以继续进头寸或反手")
    content.append("2. **加仓在盈利后**：必须在盈利的基础上加仓，不在亏损基础上加仓")
    content.append("3. **区间分批建仓**：在关键区间内分多次建仓，降低平均成本")
    content.append("4. **统一止损**：区间分批建仓时，统一止损放在区间下方")
    content.append("5. **风险可控**：每次加仓都要确保风险可控")
    content.append("")
    content.append("---")
    content.append("")
    
    return "\n".join(content)

if __name__ == '__main__':
    content = generate_position_management_update()
    try:
        print(content)
    except UnicodeEncodeError:
        pass
    
    # 保存到文件
    with open('De_position_management.md', 'w', encoding='utf-8') as f:
        f.write(content)
    print("\n头寸管理策略已保存到: De_position_management.md", file=sys.stderr)




