#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
更新De.交易系统：融入Vegas突破后支撑转换规则
"""

import sys

def generate_breakthrough_rules():
    """生成Vegas突破规则说明"""
    
    rules = []
    rules.append("## 九、Vegas通道突破后支撑转换规则（2025年12月24日更新）")
    rules.append("")
    rules.append("### 9.1 核心概念：突破后支撑转换")
    rules.append("")
    rules.append("**De.的原话**: \"但是价格突破了5分钟的vegas那这就成了支撑\"")
    rules.append("")
    rules.append("**核心原理**:")
    rules.append("- 当价格**突破**Vegas通道（EMA144/169）后，Vegas通道从**阻力**转换为**支撑**")
    rules.append("- 价格回踩到Vegas通道，如果**不破**，那就是**继续做多**的信号")
    rules.append("- 这是经典的**阻力变支撑**原理在Vegas通道上的应用")
    rules.append("")
    rules.append("### 9.2 交易规则")
    rules.append("")
    rules.append("#### 规则1：突破确认")
    rules.append("")
    rules.append("**识别标准**:")
    rules.append("- 价格突破Vegas通道上沿（EMA169）")
    rules.append("- 突破时出现**大阳K线**（实体大，成交量放大）")
    rules.append("- 突破后价格在Vegas通道上方运行")
    rules.append("")
    rules.append("**交易指导**:")
    rules.append("✅ 突破后，Vegas通道（特别是EMA169）成为**支撑位**")
    rules.append("✅ 等待价格回踩到Vegas通道附近")
    rules.append("✅ 如果价格在Vegas上方获得支撑（不破），做多信号")
    rules.append("")
    rules.append("#### 规则2：回补Vegas不破做多")
    rules.append("")
    rules.append("**De.的原话**: \"回补vegas不破，那就是继续多\"")
    rules.append("")
    rules.append("**识别标准**:")
    rules.append("- 价格突破Vegas通道后，回调到Vegas通道附近")
    rules.append("- 价格在Vegas通道（EMA144/169）上方获得支撑")
    rules.append("- 出现看涨K线信号（下影线、锤子线、大阳线等）")
    rules.append("")
    rules.append("**交易指导**:")
    rules.append("✅ **入场**: 价格回踩到Vegas通道上方，获得支撑确认后")
    rules.append("✅ **止损**: 放在Vegas通道下方2-3%（如87562下面）")
    rules.append("✅ **止盈**: 根据大阳K线判断，可以设置多个目标位")
    rules.append("")
    rules.append("#### 规则3：大阳K线 + 保本单策略")
    rules.append("")
    rules.append("**De.的原话**: \"你看5分钟这大阳k就不用着急止盈了，挂保本，止损放在87562下面，这样能吃到400点，如果没被止损，可以吃到883，那就是1200点\"")
    rules.append("")
    rules.append("**识别标准**:")
    rules.append("- 出现**大阳K线**（实体大，涨幅明显）")
    rules.append("- 成交量放大")
    rules.append("- 价格在Vegas通道上方")
    rules.append("")
    rules.append("**交易指导**:")
    rules.append("✅ **不着急止盈**: 大阳K线表示强势，可以持有更久")
    rules.append("✅ **挂保本单**: 盈利后（通常400点以上），移动止损到入场价")
    rules.append("✅ **止损设置**: 放在关键支撑位下方（如87562下面）")
    rules.append("✅ **目标位设置**:")
    rules.append("  - 第一目标: 400点（保守）")
    rules.append("  - 第二目标: 1200点（激进，如883）")
    rules.append("  - 如果没被止损，可以吃到更高目标")
    rules.append("")
    rules.append("### 9.3 实战案例")
    rules.append("")
    rules.append("**案例**: 价格突破5分钟Vegas通道")
    rules.append("")
    rules.append("**情况**:")
    rules.append("- 5分钟Vegas通道: EMA144 = 87500, EMA169 = 87600")
    rules.append("- 价格突破到88000（突破Vegas通道）")
    rules.append("- 出现大阳K线")
    rules.append("")
    rules.append("**De.的策略**:")
    rules.append("1. 确认突破: 价格突破Vegas通道，Vegas成为支撑")
    rules.append("2. 等待回踩: 价格回踩到879-882区间（Vegas通道附近）")
    rules.append("3. 确认支撑: 如果价格在Vegas上方不破，做多")
    rules.append("4. 设置止损: 止损放在87562下面（Vegas通道下方）")
    rules.append("5. 挂保本单: 盈利400点后，移动止损到入场价")
    rules.append("6. 目标位: 第一目标400点，第二目标1200点（883）")
    rules.append("")
    rules.append("**交易指导**:")
    rules.append("✅ 突破后，Vegas通道从阻力变为支撑")
    rules.append("✅ 回踩不破 = 继续做多")
    rules.append("✅ 大阳K线 = 不着急止盈，可以持有更久")
    rules.append("✅ 保本单 = 锁定利润，降低风险")
    rules.append("")
    rules.append("### 9.4 更新交易检查清单")
    rules.append("")
    rules.append("**Vegas突破检查**:")
    rules.append("□ 价格是否突破Vegas通道？（突破后Vegas成为支撑）")
    rules.append("□ 是否出现大阳K线？（强势信号）")
    rules.append("□ 价格是否回踩到Vegas通道附近？")
    rules.append("□ 回踩时是否在Vegas上方获得支撑？（不破）")
    rules.append("□ 是否设置了止损？（Vegas通道下方2-3%）")
    rules.append("□ 是否挂保本单？（盈利后移动止损到入场价）")
    rules.append("")
    rules.append("### 9.5 重要提醒")
    rules.append("")
    rules.append("1. **突破后支撑转换**: 价格突破Vegas通道后，Vegas从阻力变为支撑")
    rules.append("2. **回补不破做多**: 价格回踩到Vegas不破，继续做多")
    rules.append("3. **大阳K线不着急止盈**: 大阳K线表示强势，可以持有更久")
    rules.append("4. **保本单锁定利润**: 盈利后移动止损到入场价，锁定利润")
    rules.append("5. **多目标位设置**: 第一目标保守（400点），第二目标激进（1200点）")
    rules.append("")
    rules.append("---")
    rules.append("")
    
    return "\n".join(rules)

if __name__ == '__main__':
    rules = generate_breakthrough_rules()
    try:
        print(rules)
    except UnicodeEncodeError:
        pass
    
    # 保存到文件
    with open('De_vegas_breakthrough_rules.md', 'w', encoding='utf-8') as f:
        f.write(rules)
    print("\n规则已保存到: De_vegas_breakthrough_rules.md", file=sys.stderr)

